Doc/minor improvement
grafana/faro-web-sdk pull request #227
Opened 2023-07-03 14:16 UTC by AMontagu

## Description

Added minor improvement as specified in https://github.com/grafana/faro-web-sdk/issues/131#issuecomment-1470427538

Also integrate https://github.com/grafana/faro-web-sdk/pull/226 but keep separated if some change in this one are not wanted. If wanted 226 can be close and change made here or 226 can be merge and this rebased after it.

2023-07-03 14:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/faro-web-sdk?pullRequest=227) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/faro-web-sdk?pullRequest=227) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/faro-web-sdk?pullRequest=227) it.</sub>

2023-07-27 10:32 UTC, codecapitano commented on docs/sources/tutorials/quick-start-browser.md
> +By default opentelemetry's XMLHttpRequestInstrumentation and FetchInstrumentation
```suggestion
By default, OpenTelemetry's XMLHttpRequestInstrumentation and FetchInstrumentation inject the traceparent header only into requests sent to the same origin as the current window. To this functionality to other origins, you can enable it by setting up propagateTraceHeaderCorsUrls as shown below.
```

2023-07-27 10:33 UTC, codecapitano commented on docs/sources/tutorials/quick-start-browser.md
> +  propagateTraceHeaderCorsUrls: [new RegExp("BACKEND_SERVER(S)_REGEX")] // This is a list of spécifique URI or regex
// This is a list of specific URIs or regular exprressions
```suggestion
  propagateTraceHeaderCorsUrls: [new RegExp("BACKEND_SERVER(S)_REGEX")] // This is a list of spécifique URI or regex 
```

2023-07-27 11:06 UTC, AMontagu commented
@codecapitano Reviews done

2023-07-27 11:19 UTC, codecapitano requested changes
Hi @AMontagu this is a great enhancement of the docs 🙏 
Just some minor changes to do.

2023-07-27 11:19 UTC, codecapitano commented on docs/sources/tutorials/quick-start-browser.md
```suggestion
The following example, demonstrates how to configure OpenTelemetry manually using the `FaroTraceExporter`. To achieve this, we call the `faro.api.initOTEL` function with the `OTELTraceAPI` and `OTELContextAPI` as parameters.

If you want to change or modify the instrumentations used, you can easily achieve this by utilizing the [instrumentations option](https://github.com/grafana/faro-web-sdk/blob/main/packages/web-tracing/src/types.ts) within the `TracingInstrumentation` class.
```

2023-07-27 11:19 UTC, codecapitano commented on docs/sources/tutorials/quick-start-browser.md
> +// please note that this instrumentation come from open telemetry and can't be used directly
Please be aware that this instrumentation originates from OpenTelemetry and cannot be used directly in the initializeFaro instrumentations options. If you wish to configure these instrumentations using the initializeFaro function, please utilize the instrumentations options within the TracingInstrumentation class.

2023-07-27 11:19 UTC, codecapitano commented on docs/sources/tutorials/quick-start-browser.md
> +Enable faro internal logger:
```suggestion
To enable the Faro internal logger, follow these steps:
```

2023-07-27 11:19 UTC, codecapitano commented on docs/sources/tutorials/quick-start-browser.md
> +  internalLoggerLevel: InternalLoggerLevel.VERBOSE, // Values possible: OFF, ERROR, WARN, INFO, VERBOSE
```suggestion
  internalLoggerLevel: InternalLoggerLevel.VERBOSE, // Possible values are: OFF, ERROR, WARN, INFO, VERBOSE
```

2023-07-27 11:19 UTC, codecapitano commented on docs/sources/tutorials/quick-start-browser.md
> +Enable opentelemetry debug logger:
```suggestion
To enable the OpenTelemetry debug logger, follow these steps:
```

2023-07-27 11:23 UTC, codecapitano commented
@AMontagu the built is failing due to some Linter errors (Line 197). I think most of them are related to line length which must not exceed 120 characters.

2023-08-07 16:59 UTC, AMontagu commented
@codecapitano Change requested done, commit squased and CI passing.

2023-08-15 08:37 UTC, codecapitano requested changes
Hi @AMontagu there's only a small thing left. I think this happened by auto applying the suggestion.

2023-08-15 08:37 UTC, codecapitano commented on docs/sources/tutorials/quick-start-browser.md
> +To enable it to others backend please set up propagateTraceHeaderCorsUrls as show below.
```suggestion
By default, OpenTelemetry's XMLHttpRequestInstrumentation and FetchInstrumentation
inject the traceparent header only into requests send to the same origin as the current window.
To enable this functionality for other origins, you can enable it by setting up propagateTraceHeaderCorsUrls as shown below.
```

2023-08-16 07:58 UTC, codecapitano approved these changes
LGTM 🦖 Thank you so much for your contribution and patience  🙏

2023-08-16 07:59 UTC, merged