Check for undefined faro instance
grafana/faro-web-sdk pull request #757
Opened 2024-12-05 17:23 UTC by edkimmel

## Why

If storage throws an exception during the module init calls to isWebStorageAvailable, the global faro instance is not set and this crashes.

## What

Optional chain the faro instance itself in this catch block.

## Links

## Checklist

- [ ] Tests added
- [ ] Changelog updated
- [ ] Documentation updated

2024-12-05 17:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/faro-web-sdk?pullRequest=757) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/faro-web-sdk?pullRequest=757) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/faro-web-sdk?pullRequest=757) it.</sub>

2024-12-06 12:28 UTC, kpelelis requested changes
Hey @edkimmel, thank you so much for your interest and support in the project, as well as the time you allocated to work on this. I really appreciate it, although this is a small change, would you be able to provide a screenshot or a log, or ideally a test case that this might fail? From my understanding, the faro instance will be instantatiated [here](https://github.com/grafana/faro-web-sdk/blob/main/packages/core/src/sdk/registerFaro.ts#L13).

To be clear, I am more than happy to merge this, but I am only marking it as 'Request changes' to make sure we resolve the conversation

2024-12-06 12:28 UTC, kpelelis commented on packages/web-sdk/src/utils/webStorage.ts
> +    // this is called during module init, when the global instance may not be available
This is not necessarily called during global module init if you would be able to rephrase the comment for clarity.

2024-12-11 15:14 UTC, edkimmel commented
The logs we are seeing on our end are `TypeError: Cannot read property 'internalLogger' of undefined`.  

I have not been able to reproduce locally.  Scanning through faro, I believe this is the only callsite that could produce that error.  The other calls to faro.internalLogger all check some other property of the global faro instance (faro.config) first, which would be the line thrown from instead.

2024-12-16 10:16 UTC, kpelelis commented
> The logs we are seeing on our end are `TypeError: Cannot read property 'internalLogger' of undefined`.
> 
> I have not been able to reproduce locally. Scanning through faro, I believe this is the only callsite that could produce that error. The other calls to faro.internalLogger all check some other property of the global faro instance (faro.config) first, which would be the line thrown from instead.

Hey once again. I was on PTO last week so apologies for catching up with your replies a week later. Do you have any other stack traces that might be helpful? Although I am leaning towards your original change being the solution. I just want to get more context so that we can have precedence and ideally create a test for it

2025-01-30 09:02 UTC, codecapitano commented
Hi @edkimmel want to follow up on this.

Do you still run into the issue?

2026-07-29 15:23 UTC, kpelelis commented
I will be closing this due to inactivity

2026-07-29 15:23 UTC, closed without merging